# server
server:
    controller:
        prefix: /

# Configurações do H2
spring:
    h2:
        console:
            enabled: true
            path: "/h2"
# Data source
    datasource:
        url: "jdbc:h2:mem:template_db"
        username: "sa"
        password:
        driver-class-name: "org.h2.Driver"
        initialization-mode: "always"
